spring:
  profiles:
    active: aws

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

log:
  export:
    path: src/main/log

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

payment:
  toss:
    test_client_api_key : test_ck_DnyRpQWGrNq0JvqNMAA0VKwv1M9E
    test_secrete_api_key : test_sk_0RnYX2w532z6Mm5Ll1Qg3NeyqApQ
    success_url : "http://localhost:8080/api/v1/payments/toss/success"
    fail_url : "http://localhost:8080/api/v1/payments/toss/fail"

