spring:
  batch:
    jdbc:
      initialize-schema: always  # 배치 메타데이터 테이블 자동 생성
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: false # JobLauncherApplicationRunner 비활성화
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #quokka_travel
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    # root
    username: ${DB_USERNAME}
    # 1q2w3e4r5t
    password: ${DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 이메일을 전송할 주체의 이메일 주소 (host mail)
    password: ${APP_PASSWORD} # 해당 계정으로 발급받은 App password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: localhost:9200

  rabbitmq:
    host: localhost           # RabbitMQ host ip
    port: 5672                # RabbitMQ port
    username: guest # RabbitMQ 웹 관리 콘솔 아이디
    password: guest # RabbitMQ 웹 관리 콘솔 비밀번호


jwt:
  secret:
    key: ${JWT_SECRET_KEY}

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}  # 로컬 환경에서는 실제 키 대신 테스트 키를 넣거나 빈 값으로 두기
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}