spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #quokka_travel
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    # root
    username: ${DB_USERNAME}
    # 1q2w3e4r5t
    password: ${DB_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: localhost

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: 1234

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

slack:
  webhook-url: https://hooks.slack.com/services/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

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}  # 로컬 환경에서는 실제 키 대신 테스트 키를 넣거나 빈 값으로 두기
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}