spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${AWS_DB_IP}:3306/quokka_travel # quokka_travel_m
      username: root
      password: ${AWS_DB_PW}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${AWS_DB_IP}:3307/quokka_travel
      username: root
      password: ${AWS_DB_PW}

  data:
    redis:
      host: ${AWS_DB_IP}  # AWS ElastiCache Redis 엔드포인트
      port: 6379
      password: 1234

  elasticsearch:
    uris: ${AWS_ELASTIC_SEARCH_IP}:9200
    password: ${AWS_ELASTIC_SEARCH_PW}
    username: elastic
    connection-timeout: 1s
    socket-timeout: 30s




jwt:
  secret:
    key: ${JWT_SECRET_KEY}

slack:
  webhook-url: https://hooks.slack.com/services/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

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}   # 실제 운영 환경의 AWS 액세스 키와 시크릿 키 사용
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}