spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quokka_travel
    username: root
    password: 1q2w3e4r5t

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

log:
  export:
    path: src/main/log

logging:
  level:
    root: info