spring:
  profiles:
    active: aws

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

server:
  tomcat:
    mbeanregistry:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

log:
  export:
    path: src/main/log

logging:
  level:
    root: info
    org.springframework.cache: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

payment:
  toss:
    test_client_api_key : ${TOSS_PAYMENT_CLIENT_KEY}
    test_secret_api_key : ${TOSS_PAYMENT_SECRET_KEY}
    success_url : ${TOSS_PAYMENT_SUCCESS_URL}
    fail_url : ${TOSS_PAYMENT_FAIL_URL}

management:
  endpoint:
    health:
      show-components: always # health 컴포넌트의 상태 정보만 간략하게 노출
      #show-details: always 세부사항 볼 때
  endpoints:
    web:
      exposure:
        include: "*"