spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://13.125.107.26:3306/quokka_travel
      username: root
      password: 1234
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://13.125.107.26:3307/quokka_travel
      username: root
      password: 1234

  data:
    redis:
      host: <REDIS_ENDPOINT>  # AWS ElastiCache Redis 엔드포인트
      port: 6379

jwt:
  secret:
    key: ${JWT_SECRETKEY}

slack:
  webhook-url: https://hooks.slack.com/services/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

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}   # 실제 운영 환경의 AWS 액세스 키와 시크릿 키 사용
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}