POST http://43.202.0.210:9200/accommodations2/_search
Content-Type: application/json
Authorization: Basic ZWxhc3RpYzoxMjM0NTY=

{
  "query": {
    "match_phrase_prefix": {
      "name_partial": "아침 햇살이 아름다운 숲 속 산골마을 펜션"
    }
  }
}


